# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-J3dHyNj2cr57FyYKotdPoURT14Q_El

**Introduction to NumPy**


*  NumPy is a Python package and it stands for numerical python
*   Fundamental package for numerical computations in Python
*  Supports N-dimensional array objects that can be used for processing multidimensional data
*  Supports different data-types

**Array**

*  An array is a data structure that stores values of same data type
*  Lists can contain values corresponding to different data types.
* Arrays in python can only contain values corresponding to same data type

**NumPy Array**

* A numpy array is a grid of values, all of thes sarne type. and is i indexeds tuple of nonnegative i integers
* The number of dimensions is the rank of the array
* The shape of an array is a tuple of integers giving the size of the array along each dimension

# Creation of array
"""

my_list=[1,2,3,4,5,6]
print(my_list)

import  numpy as np
array=np.array(my_list,dtype=int)
print(array)

print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

array2=array.reshape(3,2)
print(array2)
array2.shape

array3=array.reshape(3,-1)
print(array3)
print(array3.ndim)

my_list2=[1,2,3,4,5]
my_list3=[2,3,4,5,6]
my_list4=[9,7,6,8,9]
mul_arr=np.array([my_list2,my_list3,my_list4])
print(mul_arr)
print(mul_arr.shape)

mul_arr.reshape(1,15)

"""NumPY-Attributes"""

a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

a.shape=(3,2)
print(a)

b=a.reshape(3,2)
print(b)

r=range(24)
print(r)

a=np.arange(24)
print(a)
print(a.ndim)

b=a.reshape(6,4,1)
print(b)

"""# numpy itemsize

---

This array attribute returns the length of each elaement of array of array in bytes
"""

x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

x=np.array([1,2,3,4,5],dtype=np.float32)
print(x.itemsize)

"""#NumPy Arithmetic operations"""

x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(y)

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))
print(x.dot(y))

print(x/y)
print(np.divide(x,y))

print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

