# -*- coding: utf-8 -*-
"""python for data science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1qzND5l12OZqRruxA-iREe9kCcFHzZh
"""

#1)What is the output of the following code?
a=3
b="12"
print(a*b)
#ans: 121212

#2)What is the output of the following code?
c=-9//7
print(c)
#ans: -2

#3)Consider a following code snippet. What is a data type of y?
x=5
y=str(float(y))
print(y)
#ans: Code will throw an error.

#8)Predict the output of the following code.
t=10
r=5
d=3
ans = t+r%d
print(ans)
"""a)12.0
 b)12
 c)11.667
 d)11"""
 #ans: b

#9)Given two variables, j = 6 and g = 3.3. If both normal division and floor division operators were used to divide j by g, what would be the data type of the value obtained from the operations?
"""a)int, int
 b)float, float
 c)float, int
 d)int, float"""
j=6
g=3.3
print(j/g)
print(j//g)
#ans: b

#10)Let a = 5 (101 in binary) and b = 3 (011 in binary). What is the result of the following operation?
v=5
s=3
print(v&s)
"""a)3
 b)7
 c)5
 d)1"""
 #ans: d